name: maxway_clone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  keyboard_dismisser: ^3.0.0
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  pinput: ^3.0.1
  get_it: ^7.6.4
  chuck_interceptor: ^2.0.4
  dio_retry_plus: ^2.0.1
  share_plus: ^7.1.0
  # internet checker
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  yandex_mapkit: ^3.3.3
  flutter_cupertino_datetime_picker: ^3.0.0
  lite_rolling_switch: ^1.0.1
  either_dart: ^1.0.0
  injectable_generator: ^2.1.6
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg_icon/
    - assets/png_image/
